id: P4CCCCB2A
initial_creation_type: input
source_metadata:
  Title: Aririab
  Editor: '-'
  Publisher: Soka University
  Place of Publication: Japan
  Year: '2013'
  मैत्रेयव्याकरण:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2019'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:20:34.133320'
last_modified_at: '2022-03-08T17:20:34.133329'
